pod 'EstimoteSDK', '~> 1.3.0'
pod 'Parse-iOS-SDK', '~> 1.2'
pod 'PulsingHalo', '~> 0.0.1'
pod 'MagicalRecord'
pod 'DateTools'
pod 'Canvas'

post_install do | installer |
  require 'fileutils'
  FileUtils.cp_r('Pods/Pods-acknowledgements.plist', 'iPUT/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end